// build.js - Generates config.js during Vercel/CI deployment from environment variables
import fs from 'fs';

const firebaseConfig = {
  apiKey: process.env.FIREBASE_API_KEY || "",
  authDomain: process.env.FIREBASE_AUTH_DOMAIN || "",
  projectId: process.env.FIREBASE_PROJECT_ID || "",
  storageBucket: process.env.FIREBASE_STORAGE_BUCKET || "",
  messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || "",
  appId: process.env.FIREBASE_APP_ID || "",
  measurementId: process.env.FIREBASE_MEASUREMENT_ID || ""
};

if (process.env.FIREBASE_API_KEY) {
  const content = `// Auto-generated by Vercel build step\nexport const firebaseConfig = ${JSON.stringify(firebaseConfig, null, 2)};\n`;
  fs.writeFileSync('config.js', content, 'utf8');
  console.log('✅ Successfully generated config.js from Vercel environment variables.');
} else {
  console.log('ℹ️ No FIREBASE_API_KEY env detected. Using local config.js if present.');
}
